### ISSUE TITLE
Bug report [Forge / Fabric] speak_distance messages

### ISSUE THREAD

**Issue by ysefwakil** [samolego/Taterzens#137]
**Describe the bug**

**Platform(s)**

- [x] Fabric
- [] Forge

**Environment(s)**

- [] Singleplayer
- [x] Server

**Versions**
* Minecraft 1.19.2
* Taterzens 1.11.1

**To Reproduce**
1. Launch server '...'
2. Run '....'
3. Right-click '....'

**Expected behavior**
Ability to change speak_distance for messages

speak_distance is not changing. I am moving 10 blocks away and messages are not being sent to me

**Comment by ysefwakil** [comment]
Even using: /taterzens config edit messages speakDistance 20

If I am over 3 blocks I still don't get any messages

**Comment by samolego** [comment]
Thanks for reporting, will test it when I have time

**Comment by MagicSweet-dev** [comment]
This is true, I also experienced this. 

The issue is in [this](https://github.com/samolego/Taterzens/blob/2ce633d9e3065d6730aeeaaceaa21853761684a1/common/src/main/java/org/samo_lego/taterzens/npc/TaterzenNPC.java#L558) piece of code. The problem that the box only gets inflated by 4.0 blocks, so the all the entities outside this box won't get captured and, as a result, receive a message. 

I could PR a fix for if that's okay @samolego

**Comment by samolego** [comment]
Thanks for pointing it out!
I'm glad you're willing to help, though rn developing is ... stale. I don't wanna steal your time, as mod might take a long while to be released for the new version.

If you decide to do it anyway, please use `rewrite/polymer` as the base.
Currently the only issue there (which is pushing back the release) is gameprofiles not reloading (name changes, skin changes do not reflect the right state).
