### ISSUE TITLE
Taterzen and Velocity

### ISSUE THREAD

**Issue by Gontier-Julien** [samolego/Taterzens#26]
Hi i want to use an npc to do a `</server Lobby>`, but it isn't working.

So far i've tested this: `</npc edit commands add execute at --clicker-- run server Lobby>`, but it always trow me `<Incorrect argument for command "...ker-- run server Lobby<--[here]">`

**Comment by samolego** [comment]
server command sadly isn't registered on server and is "caught" by a velocity. Taterzen commands would need to be reconfigured to support Velocity.

**Comment by Gontier-Julien** [comment]
> server command sadly isn't registered on server and is "caught" by a velocity. Taterzen commands would need to be reconfigured to support Velocity.

So it possible? Is that something that is possible to do?

**Comment by James103** [comment]
For example, instead of the command to be added being interpreted as "redirect to start of command, just like `execute ... run <command>`", the command to be add can just be a "greedy string" instead (taking the rest of the command as a single argument), just like Carpet mod's `tick warp <ticks> <tail command>` where `<tail command>` is a "greedy string".

An alternative idea would allow for the following syntax:
* `npc edit commands add <command>` preserves the current behavior.
* `npc edit commands add_custom <custom_command>` where `<custom_command>` is any text that will be sent as a chat message on behalf of the clicker (such as a command, which will then be executed on behalf of the clicker).

**Comment by samolego** [comment]
Fixed in 017092ea4e0144115e143c997fa933113928844e
