### ISSUE TITLE
NPC forced_look heads no longer move lef/right in v1.3.2 - only up/down

### ISSUE THREAD

**Issue by CruxCraft** [samolego/Taterzens#50]
in v1.3.0 heads that were FORCED_LOOK followed the player correctly, and this is now partially broken

I was very much looking forward to this current version, as it added velocity server command support, however now the bodies follow horizontally while the heads only follow vertically. The NPCs look up and down in my direction, but won't turn their head to follow me anymore... it's very odd feeling having their gaze in one direction while the shoulders turn instead to follow me...

Happy to have server commands which is more important, but thought I would let you know about that...

**Comment by CruxCraft** [comment]
I was able to go through all of our NPCs and change FORCED_LOOK to LOOK and it seems like that took care of it... not sure what the difference was before

**Comment by samolego** [comment]
Humm, thanks for reporting, seems like I'll need to release 1.3.3 :P

**Comment by CruxCraft** [comment]
no worries, and it isnt a big deal as it was easily fixable by going around and:
/npc select
//taterzens config reload

**Comment by samolego** [comment]
Why was this closed?

**Comment by maewine** [comment]
Hi - I'm using version 1.11.7 with fabric 1.20.1 and I'm having this same issue, except changing their movement to LOOK instead of FORCED_LOOK doesn't fix it like the user above - neither fixed the head issue. The whole body turns but not even all the way, just sort of three quarters of the way in the direction of the character. 

Up and down look works as expected, with head actually turning. But when you walk by/walk up to them, it doesn't work.
